# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66059ff050c7f714cc9cebfc33ce624feacb690f5d0f0363a65c806f753292d758de9a22800b680ef1f907a8550888bd6d82de3b0477491c8d26a5d60f208732

test:
  secret_key_base: defb69f03a2106d50e765653e327d278653a7b73786faf0ed311f96a61824076f6d422207c139a015604e4ca3429bc1ff2296837c4877208676ed56eadaf8460

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
